name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-and-integration:
    name: Unit + Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@d60b41a563a30eb0109d4bd8527a3a83e5f3e7b4 # v5.5.0
        with:
          go-version: "1.24"

      - name: Build
        run: go build ./...

      - name: Test
        run: go test -race -count=1 -short ./...

  e2e:
    name: E2E Tests (self-check)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@d60b41a563a30eb0109d4bd8527a3a83e5f3e7b4 # v5.5.0
        with:
          go-version: "1.24"

      - name: Self-Check Tests
        run: go test -race -count=1 -run 'TestRunSelfCheck' -timeout 30m ./cmd/gaze/...
